package com.autokeep.AutoKeep.Communication;

public enum ProtocolMessage {
    OK,
    WRONG_CREDENTIAL,
    LOGIN,
    USER_IS_BANNED,
    SEARCH_VEHICLE,
    NO_AVAILABLE_VEHICLES,
    ORDER,
    ORDER_FAILED,
    ORDER_BOOKED_SUCCESSFULLY,
    VIEW_ORDERS,
    USER_CHANGE_PASSWORD,
    PASSWORD_CHANGED_SUCCESSFULLY,
    CHANGING_PASSWORD_FAILED,
    USER_MODEL,
    RESERVATION_MODEL,
    VEHICLE_MODEL,
    USER_MODEL_LIST,
    RESERVATION_MODEL_LIST,
    VEHICLE_MODEL_LIST,
    RESERVATION_HISTORY,
    NO_HISTORY,
    HISTORY_RESULT,
    //Error Messages - Except ERROR all other error used for messages only
    ERROR,
    TOO_MANY_AUTHENTICATION_RETRIES,
    INTERNAL_ERROR;
}